import type { InsightSettingsResponse } from "@chatai/contracts";

export const DEFAULT_INSIGHT_SETTINGS: InsightSettingsResponse = {
  analysisPolicy: {
    finalAnalysisEnabled: true,
    liveAnalysisEnabled: true,
    liveMinIntervalMinutes: 15,
    liveMinNewMeaningfulMessages: 20,
    lowConfidenceThreshold: 0.6,
    minAnalysisMessages: 5,
    ruleFallbackEnabled: true,
  },
  featureConfig: {
    entityEnabled: true,
    insightAvailable: true,
    insightEnabled: false,
    intentEnabled: true,
    labelEnabled: true,
    qaEnabled: true,
    todoEnabled: true,
  },
  entityDictionary: [
    {
      aliases: ["白鸭绒外套", "直播间羽绒服"],
      canonicalName: "白色羽绒服",
      status: 1,
      entityType: "product",
      id: "1",
      includeInAggregation: true,
    },
  ],
  intentConfigs: [
    {
      aliases: ["查快递", "催发货", "物流不更新"],
      description: "客户咨询发货、快递进度或反馈物流异常",
      status: 1,
      id: "1",
      includeInStatistics: true,
      intentCode: "logistics_delay",
      intentName: "物流异常",
      negativeExamples: ["客户咨询退款到账时间"],
      positiveExamples: ["快递一直没更新", "什么时候发货"],
      weight: 8,
    },
    {
      aliases: ["退钱", "退货退款", "退款到账"],
      description: "客户咨询退款、退货退款或退款到账问题",
      status: 1,
      id: "2",
      includeInStatistics: true,
      intentCode: "after_sale.refund",
      intentName: "退款咨询",
      negativeExamples: ["客户只咨询发货时间"],
      positiveExamples: ["退款什么时候到账", "我要申请退款"],
      weight: 6,
    },
  ],
  labelConfigs: [
    {
      status: 1,
      id: "1",
      includeInStatistics: true,
      labelCode: "price_sensitive",
      labelName: "价格敏感",
    },
    {
      status: 1,
      id: "2",
      includeInStatistics: true,
      labelCode: "high_intent",
      labelName: "高意向",
    },
  ],
  qaRuleConfigs: [
    {
      status: 1,
      id: "1",
      ruleCode: "problem_resolution",
      ruleName: "客户问题是否解决",
      severity: "high",
    },
    {
      status: 1,
      id: "2",
      ruleCode: "clear_next_step",
      ruleName: "是否明确下一步",
      severity: "medium",
    },
  ],
  sessionization: {
    analysisDelayMinutes: 10,
    hardMaxDurationHours: 8,
    idleTimeoutMinutes: 120,
    lateArrivalWindowMinutes: 30,
    preset: "custom",
  },
};
