export {
  DEFAULT_INSIGHT_SETTINGS,
  SYSTEM_PRESET_ENTITY_DICTIONARY,
  SYSTEM_PRESET_INTENT_CONFIGS,
  SYSTEM_PRESET_LABEL_CONFIGS,
  SYSTEM_PRESET_QA_RULE_CONFIGS,
  systemPresetCodePrefix,
} from "@chatai/insights/http";
