/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface XyWapEmbedAiAssistant {
  /**
   * 自动生成话术时机([]数组，可多选)
   */
  auto_gen_types: Generated<string>;
  /**
   * 人设描述
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 关联知识集数组（xy_wap_embed_knowledge.id）
   */
  knowledge_ids: Generated<string>;
  /**
   * 关联模型（xy_wap_embed_ai_model.id）
   */
  model_id: Generated<number>;
  /**
   * 提示词模版名称
   */
  name: string;
  /**
   * 未命中知识集：1、模型自动生成，2、不推荐话术
   */
  not_hint_type: Generated<number>;
  /**
   * 父ID
   */
  parent_id: Generated<number>;
  /**
   * rag配置
   */
  rag_config: Generated<string>;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 子账号ID
   */
  sub_id: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedAiAssistantRoleSet {
  /**
   * 类别
   */
  biz_type: Generated<number>;
  /**
   * 人设描述
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 模版名称
   */
  name: string;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedAiCompletionRecord {
  /**
   * 返回数据
   */
  answer: string | null;
  /**
   * xy_wap_embed_ai_assistant.id
   */
  assistant_id: number;
  /**
   * 业务唯一标识
   */
  biz_key: string;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 执行方式：1、同步，2、实时异步，3、非实时异步
   */
  execute_mode: Generated<number>;
  /**
   * 失败原因
   */
  fail_reason: Generated<string | null>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 执行时的模型版本
   */
  model: Generated<string>;
  /**
   * 多模态内容（图片、视频等，json格式）
   */
  multi_content: string | null;
  /**
   * 填充参数
   */
  params: string | null;
  /**
   * 根据请求参数生成的提示词
   */
  prompt: string | null;
  /**
   * 推送第三方时间
   */
  push_third_time: Generated<number>;
  /**
   * 状态 0：待执行 1：执行中 2：执行完成 3：执行失败
   */
  status: Generated<number>;
  /**
   * 子账号id
   */
  sub_uid: Generated<number>;
  /**
   * 思考内容
   */
  think_content: string | null;
  /**
   * 第三方执行时间
   */
  third_exe_time: Generated<number>;
  /**
   * 第三方请求id
   */
  third_request_id: Generated<string>;
  /**
   * 第三方token使用情况
   */
  token_usage: Generated<string>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedAiModel {
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 算粒/百万Token，放大100倍的值
   */
  credit: Generated<number>;
  /**
   * 模型描述
   */
  description: Generated<string>;
  /**
   * 选择接入点
   */
  endpoint: Generated<string>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 选择模型id
   */
  model: Generated<string>;
  /**
   * 模型名称
   */
  model_name: Generated<string>;
  /**
   * 模型版本
   */
  model_version: Generated<string>;
  /**
   * 模型名称
   */
  name: string;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 思考模式
   */
  thinking_type: Generated<string>;
  /**
   * 租户id，0：UID兜底
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedContact {
  /**
   * 第三方客户头像
   */
  avatar: string;
  /**
   * 状态，1：正常
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人性别 0-未知 1-男性 2-女性
   */
  gender: number | null;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方客户名称
   */
  name: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方客户实名
   */
  real_name: string;
  /**
   * 第三方客户id
   */
  third_external_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedConvesation {
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 最后一条消息id
   */
  last_audit_info_id: Generated<number>;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  last_msgtime: number | null;
  /**
   * 置顶时间（非置顶为0）
   */
  pinned_time: Generated<number>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: Generated<string>;
  /**
   * 第三方群id
   */
  third_group_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 未读消息数
   */
  unread_cnt: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedCustomerBindRelation {
  /**
   * 该成员添加此外部联系人的时间戳
   */
  add_time: Generated<number>;
  /**
   * 绑定类型 1、普通客户，2、应用客户
   */
  bind_type: Generated<number>;
  /**
   * 是否已绑定 1、是 0、否
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 该成员对此外部联系人的描述
   */
  description: Generated<string | null>;
  /**
   * xy_work_external_contact_follow_user.id
   */
  follow_user_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 上一次侧边栏心跳时间
   */
  last_wap_heartbeat_time: Date | null;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * 该成员对此外部联系人的备注
   */
  remark: Generated<string | null>;
  /**
   * 该成员对此客户备注的手机号码，默认:[]
   */
  remark_mobiles: Generated<string | null>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupMember {
  /**
   * 群成员头像
   */
  avatar: string;
  /**
   * 成员状态。1 - 正常；0 - 已离开
   */
  biz_status: number | null;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 群席位id,xy_wap_embed_group_seat.id
   */
  group_seat_id: number;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 邀请者第三方成员id
   */
  inviter_third_userid: string;
  /**
   * 入群方式。1 - 由成员邀请入群（直接邀请入群）2 - 由成员邀请入群（通过邀请链接入群）3 - 通过扫描群二维码入群
   */
  join_scene: Generated<number | null>;
  /**
   * 入群时间戳
   */
  join_time: Generated<number>;
  /**
   * 群成员名称
   */
  name: string | null;
  /**
   * 群成员群内昵称
   */
  nickname: string | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 成员类型：0 普通成员,1 管理员,2 群主
   */
  type: number | null;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupSeat {
  /**
   * 第三方群头像
   */
  avatar: string;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方群名称
   */
  name: Generated<string | null>;
  /**
   * 第三方群公告
   */
  notice: string | null;
  /**
   * 第三方群主id
   */
  owner_third_userid: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方群备注
   */
  remark: Generated<string | null>;
  /**
   * 第三方群id
   */
  third_group_id: string;
  /**
   * 第三方群状态,0-正常/群状态正常及个人号状态正常且在线,1-异常/群被封或个人号状态异常,2-个人号被限制/开群助手的状态为被限制,3-群被限制/群的状态为被限制,4-个人号已下线/开群助手离线
   */
  third_status: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 群聊总人数
   */
  total: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedKnowledge {
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 名称
   */
  name: string;
  /**
   * 备注
   */
  remark: Generated<string>;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 子账号ID
   */
  sub_id: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedKnowledgeDoc {
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 文档类型：1：pdf 2：doc/docx 3：网页 4：excel
   */
  doc_type: number;
  /**
   * 文档地址
   */
  doc_url: Generated<string>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 归属知识集id
   */
  knowledge_id: Generated<number>;
  /**
   * 上一次同步时间
   */
  last_sync_time: Generated<number>;
  /**
   * 名称
   */
  name: string;
  /**
   * 备注
   */
  remark: Generated<string>;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 子账号ID
   */
  sub_id: Generated<number>;
  /**
   * 同步状态 0：未同步 1：已同步
   */
  sync: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedKnowledgeFaq {
  /**
   * 答案
   */
  answer: Generated<string>;
  /**
   * 关联素材ids（多个","分割）
   */
  attach_ids: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 归属知识文档id
   */
  doc_id: Generated<number>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 归属知识集id
   */
  knowledge_id: Generated<number>;
  /**
   * 上一次同步时间
   */
  last_sync_time: Generated<number>;
  /**
   * 问题
   */
  question: Generated<string>;
  /**
   * 相似问法
   */
  similar_question: Generated<string>;
  /**
   * 添加来源：1：手动添加 2：批量上传 3：聊天侧边栏添加
   */
  source: number;
  /**
   * 状态 0：已删除 1：有效
   */
  status: Generated<number>;
  /**
   * 子账号ID
   */
  sub_id: Generated<number>;
  /**
   * 同步状态 0：未同步 1：已同步
   */
  sync: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface XyWapEmbedMsgAuditInfo {
  /**
   * 外部群ID
   */
  chat_id: number | null;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 消息内容（不同的消息类型会不同）
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人ID(xy_work_external_contact.id)
   */
  external_id: Generated<number>;
  /**
   * 发送者身份：1、企业成员；2、外部联系人；3、群机器人
   */
  from_type: number | null;
  id: Generated<number>;
  /**
   * 消息id，消息的唯一标识
   */
  msgid: string;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  msgtime: Generated<number>;
  /**
   * 消息类型：文本：text； 图片：image；撤回：revoke；同意：agree；不同意：disagree；语音：voice；视频：video；名片：card；位置：location；表情：emotion；文件：file；链接：link；小程序：weapp；会话记录：chatrecord；待办：todo；投票：vote；填表：collect；红包：redpacket；会议邀请：meeting；在线文档：docmsg；MarkDown：markdown；图文：news；日程：calendar；混合：mixed
   */
  msgtype: Generated<string>;
  /**
   * 第三方消息类型
   */
  origin_msgtype: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否撤回标识 0:未撤回 1：已撤回
   */
  revoke_status: Generated<number | null>;
  /**
   * 情感分析结果 -1: 未分析 0: 无情感 1: 正面 2: 负面
   */
  sentiment: Generated<number>;
  /**
   * 第三方客户id
   */
  third_external_id: Generated<string>;
  /**
   * 第三方消息发送方id
   */
  third_from_id: Generated<string>;
  /**
   * 第三方群聊id(单聊为空)
   */
  third_group_id: Generated<string>;
  /**
   * 第三方消息接收方id(群消息为空)
   */
  third_to_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_user_id: Generated<string>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员ID(xy_work_user.id)
   */
  user_id: Generated<number>;
}

export interface XyWapEmbedRecommendAnswerRecord {
  /**
   * xy_wap_embed_ai_completion_record.id
   */
  ai_completion_record_id: Generated<number>;
  /**
   * 分析会话消息id
   */
  analyse_msg_id: Generated<number>;
  /**
   * 回答类型，1：基于知识集回答，2：未命中知识集，AI为您推荐的回复
   */
  answer_type: Generated<number>;
  /**
   * ai助手人设内容
   */
  assistant_content: string | null;
  /**
   * 关联AI助手
   */
  assistant_id: Generated<number>;
  /**
   * 群聊客户群id
   */
  chat_id: Generated<number>;
  /**
   * 聊天类型：1、单聊，2、群聊，100、测试
   */
  chat_type: number;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 单聊客户id
   */
  external_id: Generated<number>;
  /**
   * 错误原因
   */
  fail_reason: Generated<string>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 关联知识集数组（xy_wap_embed_knowledge.id）
   */
  knowledge_ids: Generated<string>;
  /**
   * 提问内容
   */
  question_content: string | null;
  /**
   * 提问多模态内容
   */
  question_multi_content: string | null;
  /**
   * 实际发送回答
   */
  real_answer: string | null;
  /**
   * 实际发送的附件id（,分割)
   */
  real_attach_ids: Generated<string>;
  /**
   * 推荐回答
   */
  recommend_answer: string | null;
  /**
   * 推荐回答字数
   */
  recommend_answer_length: Generated<number>;
  /**
   * 答案参考附件ids（,分割)
   */
  ref_attach_ids: Generated<string>;
  /**
   * 答案参考doc ids（,分割）
   */
  ref_doc_ids: Generated<string>;
  /**
   * 答案参考faq ids（,分割)
   */
  ref_faq_ids: Generated<string>;
  /**
   * 参考资料
   */
  ref_info: string | null;
  /**
   * 关联消息ids（,分割）
   */
  relate_msg_ids: string | null;
  /**
   * 发送回答时间
   */
  send_answer_time: Generated<number>;
  /**
   * 状态 0：初始化 1：推荐中 2：推荐成功 3：推荐失败 4：已发送
   */
  status: Generated<number>;
  /**
   * 总消耗算力数（百万倍放大）
   */
  suanli_cost: Generated<number>;
  /**
   * 总消耗tokens
   */
  total_token: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
  /**
   * 使用成员id(xy_work_user.id)
   */
  user_id: number;
}

export interface XyWapEmbedRecommendAnswerStatistic {
  /**
   * 服务群聊数
   */
  chat_cnt: Generated<number>;
  /**
   * 扣减算力状态：0、无需扣减，1、扣减成功，2、扣减失败
   */
  cost_status: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 服务客户数
   */
  external_cnt: Generated<number>;
  /**
   * 主键id
   */
  id: Generated<number>;
  /**
   * 推荐话术次数
   */
  recommend_answer_cnt: Generated<number>;
  /**
   * 发送话术次数
   */
  send_answer_cnt: Generated<number>;
  /**
   * 记录发生日期，当天0点单位秒
   */
  stat_date: number;
  /**
   * 消耗算粒数
   */
  suanli_cnt: Generated<number>;
  /**
   * 违规词检测次数
   */
  text_moderation_cnt: Generated<number>;
  /**
   * 推荐话术总字数
   */
  total_answer_length: Generated<number>;
  /**
   * 总消耗token数
   */
  total_token: Generated<number>;
  /**
   * 租户id
   */
  uid: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
  /**
   * 使用成员数
   */
  user_cnt: Generated<number>;
}

export interface XyWapEmbedSiderBarConfig {
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 名称
   */
  name: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否展示
   */
  show: Generated<number | null>;
  /**
   * 排序(越小越靠前，最小为1)
   */
  sort: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 页面地址
   */
  url: string;
}

export interface XyWapEmbedSubUser {
  /**
   * 登录用户名
   */
  account: string;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 账号名称
   */
  name: string;
  /**
   * 加密后的密码
   */
  password: string;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * 加密校验码
   */
  salt: string;
  /**
   * 状态：1正常，2禁用，0删除
   */
  status: Generated<number>;
  /**
   * 账号类型：0子账户，1主账户
   */
  type: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedUserRelation {
  /**
   * appid
   */
  appid: string;
  /**
   * 状态 1、正常 -1、删除
   */
  biz_status: Generated<number>;
  /**
   * 客户端key
   */
  client_key: Generated<string>;
  /**
   * 客户端secret
   */
  client_secret: Generated<string>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 结束时间
   */
  end_time: Generated<number | null>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 偏移量
   */
  iv_parameter: string;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * secret
   */
  secret: string;
  /**
   * 开始时间
   */
  start_time: Generated<number | null>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedUserSeat {
  /**
   * 关联AI助手，xy_wap_embed_ai_assistant.id
   */
  assistant_id: Generated<number>;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 当前接管子账号id(xy_wap_embed_sub_user.id)
   */
  host_sub_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 是否在线，是否在线 0-不在线 1-在线
   */
  is_online: number | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员头像
   */
  third_avatar: string;
  /**
   * 第三方成员名称
   */
  third_user_name: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * xy_work_user.id
   */
  user_id: number | null;
}

export interface XyWapEmbedUserSeatSubRelation {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * 子账号id(xy_wap_embed_sub_user.id)
   */
  sub_id: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员席位id(xy_wap_embed_user_seat.id)
   */
  user_seat_id: Generated<number>;
}

export interface DB {
  xy_wap_embed_ai_assistant: XyWapEmbedAiAssistant;
  xy_wap_embed_ai_assistant_role_set: XyWapEmbedAiAssistantRoleSet;
  xy_wap_embed_ai_completion_record: XyWapEmbedAiCompletionRecord;
  xy_wap_embed_ai_model: XyWapEmbedAiModel;
  xy_wap_embed_contact: XyWapEmbedContact;
  xy_wap_embed_convesation: XyWapEmbedConvesation;
  xy_wap_embed_customer_bind_relation: XyWapEmbedCustomerBindRelation;
  xy_wap_embed_group_member: XyWapEmbedGroupMember;
  xy_wap_embed_group_seat: XyWapEmbedGroupSeat;
  xy_wap_embed_knowledge: XyWapEmbedKnowledge;
  xy_wap_embed_knowledge_doc: XyWapEmbedKnowledgeDoc;
  xy_wap_embed_knowledge_faq: XyWapEmbedKnowledgeFaq;
  xy_wap_embed_msg_audit_info: XyWapEmbedMsgAuditInfo;
  xy_wap_embed_recommend_answer_record: XyWapEmbedRecommendAnswerRecord;
  xy_wap_embed_recommend_answer_statistic: XyWapEmbedRecommendAnswerStatistic;
  xy_wap_embed_sider_bar_config: XyWapEmbedSiderBarConfig;
  xy_wap_embed_sub_user: XyWapEmbedSubUser;
  xy_wap_embed_user_relation: XyWapEmbedUserRelation;
  xy_wap_embed_user_seat: XyWapEmbedUserSeat;
  xy_wap_embed_user_seat_sub_relation: XyWapEmbedUserSeatSubRelation;
}

export type Database = DB;
