/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface XyWapEmbedContact {
  /**
   * 第三方客户头像
   */
  avatar: string;
  /**
   * 状态，1：正常
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人性别 0-未知 1-男性 2-女性
   */
  gender: number | null;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方客户名称
   */
  name: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方客户实名
   */
  real_name: string;
  /**
   * 第三方客户id
   */
  third_external_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedConversation {
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 最后一条消息id
   */
  last_audit_info_id: Generated<number>;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  last_msgtime: number | null;
  /**
   * 置顶时间（非置顶为0）
   */
  pinned_time: Generated<number>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: Generated<string>;
  /**
   * 第三方群id
   */
  third_group_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 未读消息数
   */
  unread_cnt: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 是否已识别
   */
  verified: Generated<number>;
}

export interface XyWapEmbedCustomerBindRelation {
  /**
   * 该成员添加此外部联系人的时间戳
   */
  add_time: Generated<number>;
  /**
   * 绑定类型 1、普通客户，2、应用客户
   */
  bind_type: Generated<number>;
  /**
   * 是否已绑定 1、是 0、否
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 该成员对此外部联系人的描述
   */
  description: Generated<string | null>;
  /**
   * xy_work_external_contact_follow_user.id
   */
  follow_user_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 上一次侧边栏心跳时间
   */
  last_wap_heartbeat_time: Date | null;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * 该成员对此外部联系人的备注
   */
  remark: Generated<string | null>;
  /**
   * 该成员对此客户备注的手机号码，默认:[]
   */
  remark_mobiles: Generated<string | null>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupMember {
  /**
   * 群成员头像
   */
  avatar: string;
  /**
   * 成员状态。1 - 正常；0 - 已离开
   */
  biz_status: number | null;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 群席位id,xy_wap_embed_group_seat.id
   */
  group_seat_id: number;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 邀请者第三方成员id
   */
  inviter_third_userid: string;
  /**
   * 入群方式。1 - 由成员邀请入群（直接邀请入群）2 - 由成员邀请入群（通过邀请链接入群）3 - 通过扫描群二维码入群
   */
  join_scene: Generated<number | null>;
  /**
   * 入群时间戳
   */
  join_time: Generated<number>;
  /**
   * 群成员名称
   */
  name: string | null;
  /**
   * 群成员群内昵称
   */
  nickname: string | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 成员类型：0 普通成员,1 管理员,2 群主
   */
  type: number | null;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupSeat {
  /**
   * 第三方群头像
   */
  avatar: string;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方群名称
   */
  name: Generated<string | null>;
  /**
   * 第三方群公告
   */
  notice: string | null;
  /**
   * 第三方群主id
   */
  owner_third_userid: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方群备注
   */
  remark: Generated<string | null>;
  /**
   * 第三方群id
   */
  third_group_id: string;
  /**
   * 第三方群状态,0-正常/群状态正常及个人号状态正常且在线,1-异常/群被封或个人号状态异常,2-个人号被限制/开群助手的状态为被限制,3-群被限制/群的状态为被限制,4-个人号已下线/开群助手离线
   */
  third_status: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 群聊总人数
   */
  total: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedMsgAuditInfo {
  /**
   * 外部群ID
   */
  chat_id: number | null;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 消息内容（不同的消息类型会不同）
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人ID(xy_work_external_contact.id)
   */
  external_id: Generated<number>;
  /**
   * 发送者身份：1、企业成员；2、外部联系人；3、群机器人
   */
  from_type: number | null;
  id: Generated<number>;
  /**
   * 消息id，消息的唯一标识
   */
  msgid: string;
  /**
   * 消息id2，消息的唯一标识(支持两种类型的唯一id，可选)
   */
  msgid2: string | null;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  msgtime: Generated<number>;
  /**
   * 消息类型：文本：text； 图片：image；撤回：revoke；同意：agree；不同意：disagree；语音：voice；视频：video；名片：card；位置：location；表情：emotion；文件：file；链接：link；小程序：weapp；会话记录：chatrecord；待办：todo；投票：vote；填表：collect；红包：redpacket；会议邀请：meeting；在线文档：docmsg；MarkDown：markdown；图文：news；日程：calendar；混合：mixed
   */
  msgtype: Generated<string>;
  /**
   * 关联发送消息的操作编号
   */
  opt_no: string | null;
  /**
   * 第三方消息类型
   */
  origin_msgtype: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否撤回标识 0:未撤回 1：已撤回
   */
  revoke_status: Generated<number | null>;
  /**
   * 情感分析结果 -1: 未分析 0: 无情感 1: 正面 2: 负面
   */
  sentiment: Generated<number>;
  /**
   * 第三方客户id
   */
  third_external_id: Generated<string>;
  /**
   * 第三方消息发送方id
   */
  third_from_id: Generated<string>;
  /**
   * 第三方群聊id(单聊为空)
   */
  third_group_id: Generated<string>;
  /**
   * 第三方消息接收方id(群消息为空)
   */
  third_to_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_user_id: Generated<string>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员ID(xy_work_user.id)
   */
  user_id: Generated<number>;
}

export interface XyWapEmbedMsgAuditInfoExtend {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 消息id，消息的唯一标识
   */
  msgid: string;
  /**
   * 原始消息内容
   */
  origin_data: string | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedSiderBarConfig {
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 名称
   */
  name: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否展示
   */
  show: Generated<number | null>;
  /**
   * 排序(越小越靠前，最小为1)
   */
  sort: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 页面地址
   */
  url: string;
}

export interface XyWapEmbedSubUser {
  /**
   * 登录用户名
   */
  account: string;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 账号名称
   */
  name: string;
  /**
   * Argon2id PHC格式密码哈希
   */
  password_hash: string;
  /**
   * 预设角色：operator客服，viewer只读客服，admin管理员；主账号由type=1推导为owner
   */
  role: Generated<string>;
  /**
   * 内嵌平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 状态：1正常，2禁用，0删除
   */
  status: Generated<number>;
  /**
   * 账号类型：0子账户，1主账户
   */
  type: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedSubUserSession {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * refresh token过期时间
   */
  expires_at: Date;
  id: Generated<number>;
  /**
   * 登录IP
   */
  ip: string | null;
  /**
   * 最近刷新时间
   */
  last_used_at: Date | null;
  /**
   * refresh token哈希
   */
  refresh_token_hash: string;
  /**
   * 吊销时间
   */
  revoked_at: Date | null;
  /**
   * 会话版本，新登录时递增
   */
  session_version: Generated<number>;
  /**
   * 子账号id(xy_wap_embed_sub_user.id)
   */
  sub_user_id: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 登录设备UA
   */
  user_agent: string | null;
}

export interface XyWapEmbedUserRelation {
  /**
   * appid
   */
  appid: string;
  /**
   * 状态 1、正常 -1、删除
   */
  biz_status: Generated<number>;
  /**
   * 客户端key
   */
  client_key: Generated<string>;
  /**
   * 客户端secret
   */
  client_secret: Generated<string>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 结束时间
   */
  end_time: Generated<number | null>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 偏移量
   */
  iv_parameter: string;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * secret
   */
  secret: string;
  /**
   * 开始时间
   */
  start_time: Generated<number | null>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedUserSeat {
  /**
   * 关联AI助手，xy_wap_embed_ai_assistant.id
   */
  assistant_id: Generated<number>;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 当前接管子账号id(xy_wap_embed_sub_user.id)
   */
  host_sub_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 是否在线，是否在线 0-不在线 1-在线
   */
  is_online: number | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员头像
   */
  third_avatar: string;
  /**
   * 第三方成员名称
   */
  third_user_name: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * xy_work_user.id
   */
  user_id: number | null;
}

export interface XyWapEmbedUserSeatSubRelation {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 内嵌平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 子账号id(xy_wap_embed_sub_user.id)
   */
  sub_id: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员席位id(xy_wap_embed_user_seat.id)
   */
  user_seat_id: Generated<number>;
}

export interface DB {
  xy_wap_embed_contact: XyWapEmbedContact;
  xy_wap_embed_conversation: XyWapEmbedConversation;
  xy_wap_embed_customer_bind_relation: XyWapEmbedCustomerBindRelation;
  xy_wap_embed_group_member: XyWapEmbedGroupMember;
  xy_wap_embed_group_seat: XyWapEmbedGroupSeat;
  xy_wap_embed_msg_audit_info: XyWapEmbedMsgAuditInfo;
  xy_wap_embed_msg_audit_info_extend: XyWapEmbedMsgAuditInfoExtend;
  xy_wap_embed_sider_bar_config: XyWapEmbedSiderBarConfig;
  xy_wap_embed_sub_user: XyWapEmbedSubUser;
  xy_wap_embed_sub_user_session: XyWapEmbedSubUserSession;
  xy_wap_embed_user_relation: XyWapEmbedUserRelation;
  xy_wap_embed_user_seat: XyWapEmbedUserSeat;
  xy_wap_embed_user_seat_sub_relation: XyWapEmbedUserSeatSubRelation;
}

export type Database = DB;
