/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface XyWapEmbedBroadcastEvent {
  /**
   * 事件分类：conversation-会话
   */
  category: Generated<string>;
  /**
   * 事件分类关联id（conversation分类，则为conversation.id）
   */
  category_bind_id: Generated<string>;
  /**
   * 事件内容（不同的事件类型会不同）
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * 事件类型
   */
  event: string;
  id: Generated<number>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
}

export interface XyWapEmbedContact {
  /**
   * 第三方客户头像
   */
  avatar: Generated<string>;
  /**
   * 状态，1：正常
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人性别 0-未知 1-男性 2-女性
   */
  gender: Generated<number | null>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方客户名称
   */
  name: Generated<string>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方客户实名
   */
  real_name: Generated<string>;
  /**
   * 第三方客户id
   */
  third_external_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedConversation {
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 最后一条消息id
   */
  last_audit_info_id: Generated<number>;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  last_msgtime: number | null;
  /**
   * 置顶时间（非置顶为0）
   */
  pinned_time: Generated<number>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: Generated<string>;
  /**
   * 第三方群id
   */
  third_group_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 未读消息数
   */
  unread_cnt: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 是否已识别
   */
  verified: Generated<number>;
}

export interface XyWapEmbedCustomerBindRelation {
  /**
   * 该成员添加此外部联系人的时间戳
   */
  add_time: Generated<number>;
  /**
   * 绑定类型 1、普通客户，2、应用客户
   */
  bind_type: Generated<number>;
  /**
   * 是否已绑定 1、是 0、否
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 该成员对此外部联系人的描述
   */
  description: Generated<string | null>;
  /**
   * xy_work_external_contact_follow_user.id
   */
  follow_user_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 上一次智能工作台心跳时间
   */
  last_smart_heartbeat_time: Date | null;
  /**
   * 上一次侧边栏心跳时间
   */
  last_wap_heartbeat_time: Date | null;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * 该成员对此外部联系人的备注
   */
  remark: Generated<string | null>;
  /**
   * 该成员对此客户备注的手机号码，默认:[]
   */
  remark_mobiles: Generated<string | null>;
  /**
   * 第三方外部联系人id
   */
  third_external_userid: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupMember {
  /**
   * 群成员头像
   */
  avatar: string | null;
  /**
   * 成员状态。1 - 正常；0 - 已离开
   */
  biz_status: number | null;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 群席位id,xy_wap_embed_group_seat.id
   */
  group_seat_id: number;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 邀请者第三方成员id
   */
  inviter_third_userid: string | null;
  /**
   * 入群方式。1 - 由成员邀请入群（直接邀请入群）2 - 由成员邀请入群（通过邀请链接入群）3 - 通过扫描群二维码入群
   */
  join_scene: Generated<number | null>;
  /**
   * 入群时间戳
   */
  join_time: Generated<number>;
  /**
   * 群成员名称
   */
  name: string | null;
  /**
   * 群成员群内昵称
   */
  nickname: string | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 成员类型：0 普通成员,1 管理员,2 群主
   */
  type: number | null;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedGroupSeat {
  /**
   * 第三方群头像
   */
  avatar: Generated<string>;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 群ID，xy_work_chat.id
   */
  chat_id: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 第三方群名称
   */
  name: Generated<string | null>;
  /**
   * 第三方群公告
   */
  notice: string | null;
  /**
   * 第三方群主id
   */
  owner_third_userid: Generated<string>;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方群备注
   */
  remark: Generated<string | null>;
  /**
   * 第三方群id
   */
  third_group_id: string;
  /**
   * 第三方群状态,0-正常/群状态正常及个人号状态正常且在线,1-异常/群被封或个人号状态异常,2-个人号被限制/开群助手的状态为被限制,3-群被限制/群的状态为被限制,4-个人号已下线/开群助手离线
   */
  third_status: Generated<number>;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 群聊总人数
   */
  total: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedMsgAuditInfo {
  /**
   * 外部群ID
   */
  chat_id: number | null;
  /**
   * 会话类型：1、私聊，2、群聊
   */
  chat_type: Generated<number>;
  /**
   * 消息内容（不同的消息类型会不同）
   */
  content: string | null;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * 外部联系人ID(xy_work_external_contact.id)
   */
  external_id: Generated<number>;
  /**
   * 发送者身份：1、企业成员；2、外部联系人；3、群机器人
   */
  from_type: number | null;
  id: Generated<number>;
  /**
   * 消息id，消息的唯一标识
   */
  msgid: string;
  /**
   * 消息id2，消息的唯一标识(支持两种类型的唯一id，可选)
   */
  msgid2: string | null;
  /**
   * 消息发送时间戳，utc时间，ms单位
   */
  msgtime: Generated<number>;
  /**
   * 消息类型：文本：text； 图片：image；撤回：revoke；同意：agree；不同意：disagree；语音：voice；视频：video；名片：card；位置：location；表情：emotion；文件：file；链接：link；小程序：weapp；会话记录：chatrecord；待办：todo；投票：vote；填表：collect；红包：redpacket；会议邀请：meeting；在线文档：docmsg；MarkDown：markdown；图文：news；日程：calendar；混合：mixed
   */
  msgtype: Generated<string>;
  /**
   * 关联发送消息的操作编号
   */
  opt_no: string | null;
  /**
   * 第三方消息类型
   */
  origin_msgtype: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否撤回标识 0:未撤回 1：已撤回
   */
  revoke_status: Generated<number | null>;
  /**
   * 情感分析结果 -1: 未分析 0: 无情感 1: 正面 2: 负面
   */
  sentiment: Generated<number>;
  /**
   * 消息来源：0、默认，1、客服工作台，2、企微侧边栏
   */
  source: Generated<number>;
  /**
   * 消息状态：0、发送失败，1、发送成功
   */
  status: Generated<number>;
  /**
   * 第三方客户id
   */
  third_external_id: Generated<string>;
  /**
   * 第三方消息发送方id
   */
  third_from_id: Generated<string>;
  /**
   * 第三方群聊id(单聊为空)
   */
  third_group_id: Generated<string>;
  /**
   * 第三方消息接收方id(群消息为空)
   */
  third_to_id: Generated<string>;
  /**
   * 第三方成员id
   */
  third_user_id: Generated<string>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员ID(xy_work_user.id)
   */
  user_id: Generated<number>;
}

export interface XyWapEmbedMsgAuditInfoExtend {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 消息id，消息的唯一标识
   */
  msgid: string;
  /**
   * 原始消息内容
   */
  origin_data: string | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedSiderBarConfig {
  /**
   * 绑定类型：1、单聊，2、群聊（多选用“,”分割）
   */
  bind_types: Generated<string>;
  /**
   * 会话状态：1、正常，0、删除
   */
  biz_status: Generated<number | null>;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 名称
   */
  name: string;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 是否展示
   */
  show: Generated<number | null>;
  /**
   * 排序(越小越靠前，最小为1)
   */
  sort: Generated<number>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 页面地址
   */
  url: string;
}

export interface XyWapEmbedSubUser {
  /**
   * 登录用户名
   */
  account: string;
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 账号名称
   */
  name: string;
  /**
   * Argon2id PHC格式密码哈希
   */
  password_hash: string;
  /**
   * 内嵌平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 预设角色：operator客服，viewer客服(只读)，admin管理员；主账号由type=1推导为owner
   */
  role: Generated<string>;
  /**
   * 状态：1正常，2禁用，0删除
   */
  status: Generated<number>;
  /**
   * 账号类型：0子账户，1主账户
   */
  type: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedSubUserSession {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  /**
   * refresh token过期时间
   */
  expires_at: Date;
  id: Generated<number>;
  /**
   * 登录IP
   */
  ip: string | null;
  /**
   * 最近刷新时间
   */
  last_used_at: Date | null;
  /**
   * refresh token哈希
   */
  refresh_token_hash: string;
  /**
   * 吊销时间
   */
  revoked_at: Date | null;
  /**
   * 会话版本，新登录时递增
   */
  session_version: Generated<number>;
  /**
   * 子账号id(xy_wap_embed_sub_user.id)
   */
  sub_user_id: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 登录设备UA
   */
  user_agent: string | null;
}

export interface XyWapEmbedUserRelation {
  /**
   * appid
   */
  appid: string;
  /**
   * 状态 1、正常 -1、删除
   */
  biz_status: Generated<number>;
  /**
   * 客户端key
   */
  client_key: Generated<string>;
  /**
   * 客户端secret
   */
  client_secret: Generated<string>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 结束时间
   */
  end_time: Generated<number | null>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 偏移量
   */
  iv_parameter: string;
  /**
   * 匹配类型 1、根据名称匹配
   */
  match_type: Generated<number>;
  /**
   * 内嵌平台 1、涂色
   */
  platform: Generated<number>;
  /**
   * secret
   */
  secret: string;
  /**
   * 开始时间
   */
  start_time: Generated<number | null>;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
}

export interface XyWapEmbedUserSeat {
  /**
   * 关联AI助手，xy_wap_embed_ai_assistant.id
   */
  assistant_id: Generated<number>;
  /**
   * 席位状态： 1、已绑定 0、已注销
   */
  biz_status: Generated<number>;
  /**
   * 插入时间
   */
  create_time: Generated<Date>;
  /**
   * 当前接管子账号id(xy_wap_embed_sub_user.id)
   */
  host_sub_id: Generated<number>;
  /**
   * id
   */
  id: Generated<number>;
  /**
   * 是否在线，是否在线 0-不在线 1-在线
   */
  is_online: number | null;
  /**
   * 接入平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 第三方成员头像
   */
  third_avatar: string;
  /**
   * 第三方成员名称
   */
  third_user_name: string;
  /**
   * 第三方成员id
   */
  third_userid: string;
  /**
   * 租户id
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * xy_work_user.id
   */
  user_id: number | null;
}

export interface XyWapEmbedUserSeatSubRelation {
  /**
   * 创建时间
   */
  create_time: Generated<Date>;
  id: Generated<number>;
  /**
   * 内嵌平台 5、比邻
   */
  platform: Generated<number>;
  /**
   * 子账号id(xy_wap_embed_sub_user.id)
   */
  sub_id: Generated<number>;
  /**
   * 租户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date>;
  /**
   * 成员席位id(xy_wap_embed_user_seat.id)
   */
  user_seat_id: Generated<number>;
}

export interface XyWapEmbedInsightSyncCursor {
  create_time: Generated<Date>;
  cursor_audit_id: number;
  cursor_msgtime: number;
  id: Generated<number>;
  source: string;
  uid: number | null;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionizationConfig {
  analysis_delay_minutes: number;
  create_time: Generated<Date>;
  enabled: Generated<number>;
  hard_max_duration_hours: number;
  id: Generated<number>;
  idle_timeout_minutes: number;
  late_arrival_window_minutes: number;
  preset: string;
  rule_version: string;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedLogicalSession {
  agent_message_count: Generated<number>;
  analysis_delay_minutes: number;
  close_reason: string | null;
  conversation_id: number;
  create_time: Generated<Date>;
  current_snapshot_id: number | null;
  ended_at: number | null;
  final_snapshot_id: number | null;
  hard_max_duration_hours: number;
  id: Generated<number>;
  idle_timeout_minutes: number;
  last_meaningful_message_at: number | null;
  last_message_at: number | null;
  message_count: Generated<number>;
  next_close_at: number | null;
  rule_version: string;
  started_at: number;
  status: string;
  uid: number;
  update_time: Generated<Date>;
  customer_message_count: Generated<number>;
}

export interface XyWapEmbedLogicalSessionMessage {
  conversation_id: number;
  create_time: Generated<Date>;
  id: Generated<number>;
  included_for_ai: Generated<number>;
  meaningful_for_boundary: Generated<number>;
  message_type: string;
  occurred_at: number;
  sender_role: string;
  session_id: number;
  source_message_id: number;
  source_message_time: number;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightJob {
  attempt_count: Generated<number>;
  create_time: Generated<Date>;
  error_code: string | null;
  error_message: string | null;
  id: Generated<number>;
  idempotency_key: string;
  job_type: string;
  analysis_scope: string;
  lease_until: Date | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  priority: Generated<number>;
  rescan_task_id: number | null;
  run_after: Generated<Date>;
  status: string;
  target_id: string;
  target_type: string;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightJobArchive {
  archived_at: Generated<Date>;
  attempt_count: Generated<number>;
  create_time: Date;
  error_code: string | null;
  error_message: string | null;
  id: number;
  idempotency_key: string;
  job_type: string;
  analysis_scope: string;
  lease_until: Date | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  priority: Generated<number>;
  rescan_task_id: number | null;
  run_after: Generated<Date>;
  status: string;
  target_id: string;
  target_type: string;
  uid: number;
  update_time: Date;
}

export interface XyWapEmbedInsightRescanTask {
  analysis_scope: string;
  create_time: Generated<Date>;
  created_by: string | null;
  error_message: string | null;
  failed_sessions: Generated<number>;
  finished_at: Date | null;
  from_time: Date;
  id: Generated<number>;
  queued_sessions: Generated<number>;
  started_at: Date | null;
  status: string;
  succeeded_sessions: Generated<number>;
  to_time: Date | null;
  total_sessions: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedAnalysisRun {
  analysis_scope: string;
  cost_estimate: string | null;
  create_time: Generated<Date>;
  error_code: string | null;
  error_message: string | null;
  finished_at: Date | null;
  id: Generated<number>;
  input_token_count: number | null;
  job_id: number | null;
  mode: string;
  model_name: string | null;
  output_token_count: number | null;
  prompt_version: string | null;
  provider_code: string | null;
  raw_output_ref: string | null;
  session_id: number;
  source_message_from: number | null;
  source_message_to: number | null;
  status: string;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionInsightSnapshot {
  analysis_version: string;
  create_time: Generated<Date>;
  id: Generated<number>;
  model_profile_id: number | null;
  phase: string;
  prompt_version: string;
  rule_version: string;
  session_id: number;
  source_message_high_watermark: number | null;
  status: string;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionInsightCurrent {
  create_time: Generated<Date>;
  current_snapshot_id: number;
  id: Generated<number>;
  session_id: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionSummary {
  create_time: Generated<Date>;
  id: Generated<number>;
  session_title: string;
  snapshot_id: number;
  summary_text: string;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionSentiment {
  confidence: number | null;
  create_time: Generated<Date>;
  id: Generated<number>;
  polarity: string;
  reason: string;
  snapshot_id: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionTag {
  confidence: number | null;
  create_time: Generated<Date>;
  id: Generated<number>;
  snapshot_id: number;
  tag_code: string;
  tag_name: string;
  update_time: Generated<Date>;
  uid: number;
}

export interface XyWapEmbedSessionProblemResolution {
  agent_action_summary: string | null;
  confidence: number | null;
  create_time: Generated<Date>;
  customer_final_state: string | null;
  id: Generated<number>;
  problem_detected: number;
  problem_summary: string;
  resolution_status: string;
  snapshot_id: number;
  unresolved_reason: string | null;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionQaFinding {
  confidence: number | null;
  create_time: Generated<Date>;
  id: Generated<number>;
  passed: number;
  reason: string;
  rule_code: string;
  rule_name: string;
  severity: string;
  snapshot_id: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedSessionEntity {
  confidence: number | null;
  create_time: Generated<Date>;
  entity_id: string;
  entity_name: string;
  entity_type: string;
  id: Generated<number>;
  sentiment: string | null;
  snapshot_id: number;
  update_time: Generated<Date>;
  uid: number;
}

export interface XyWapEmbedSessionIntent {
  confidence: number | null;
  create_time: Generated<Date>;
  id: Generated<number>;
  intent_code: string;
  intent_label: string;
  snapshot_id: number;
  update_time: Generated<Date>;
  uid: number;
}

export interface XyWapEmbedSessionActionItem {
  action_type: string;
  create_time: Generated<Date>;
  due_hint: string | null;
  id: Generated<number>;
  priority: string;
  snapshot_id: number;
  status: string;
  title: string;
  update_time: Generated<Date>;
  uid: number;
}

export interface XyWapEmbedSessionFaqCandidate {
  answer_hint: string;
  confidence: number | null;
  create_time: Generated<Date>;
  id: Generated<number>;
  question: string;
  snapshot_id: number;
  status: string;
  update_time: Generated<Date>;
  uid: number;
}

export interface XyWapEmbedInsightEvidence {
  conversation_id: number;
  create_time: Generated<Date>;
  dimension_record_id: number | null;
  dimension_type: string;
  evidence_role: string;
  id: Generated<number>;
  reason: string | null;
  session_id: number;
  snapshot_id: number;
  source_message_id: number;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightAnalysisPolicy {
  create_time: Generated<Date>;
  enabled: Generated<number>;
  final_analysis_enabled: Generated<number>;
  id: Generated<number>;
  live_analysis_enabled: Generated<number>;
  live_min_interval_minutes: number;
  live_min_new_meaningful_messages: number;
  low_confidence_threshold: string;
  min_analysis_messages: Generated<number>;
  rule_fallback_enabled: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightFeatureConfig {
  create_time: Generated<Date>;
  entity_enabled: Generated<number>;
  id: Generated<number>;
  insight_enabled: Generated<number>;
  intent_enabled: Generated<number>;
  label_enabled: Generated<number>;
  last_enable_time: number | null;
  qa_enabled: Generated<number>;
  todo_enabled: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightLabelConfig {
  create_time: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  include_in_statistics: Generated<number>;
  label_code: string;
  label_name: string;
  negative_examples_json: string | null;
  positive_examples_json: string | null;
  status: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightIntentConfig {
  aliases_json: string | null;
  create_time: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  include_in_statistics: Generated<number>;
  intent_code: string;
  intent_name: string;
  negative_examples_json: string | null;
  positive_examples_json: string | null;
  sort_order: Generated<number>;
  status: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightQaRuleConfig {
  applicable_scene: string | null;
  create_time: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  judgment_criteria: string | null;
  negative_examples_json: string | null;
  positive_examples_json: string | null;
  rule_code: string;
  rule_name: string;
  severity: string;
  status: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface XyWapEmbedInsightEntityDictionary {
  aliases_json: string | null;
  attributes_json: string | null;
  canonical_name: string;
  create_time: Generated<Date>;
  entity_type: string;
  id: Generated<number>;
  include_in_aggregation: Generated<number>;
  status: Generated<number>;
  uid: number;
  update_time: Generated<Date>;
}

export interface DB {
  xy_wap_embed_analysis_run: XyWapEmbedAnalysisRun;
  xy_wap_embed_broadcast_event: XyWapEmbedBroadcastEvent;
  xy_wap_embed_contact: XyWapEmbedContact;
  xy_wap_embed_conversation: XyWapEmbedConversation;
  xy_wap_embed_customer_bind_relation: XyWapEmbedCustomerBindRelation;
  xy_wap_embed_group_member: XyWapEmbedGroupMember;
  xy_wap_embed_group_seat: XyWapEmbedGroupSeat;
  xy_wap_embed_insight_analysis_policy: XyWapEmbedInsightAnalysisPolicy;
  xy_wap_embed_insight_entity_dictionary: XyWapEmbedInsightEntityDictionary;
  xy_wap_embed_insight_evidence: XyWapEmbedInsightEvidence;
  xy_wap_embed_insight_feature_config: XyWapEmbedInsightFeatureConfig;
  xy_wap_embed_insight_job: XyWapEmbedInsightJob;
  xy_wap_embed_insight_job_archive: XyWapEmbedInsightJobArchive;
  xy_wap_embed_insight_rescan_task: XyWapEmbedInsightRescanTask;
  xy_wap_embed_insight_intent_config: XyWapEmbedInsightIntentConfig;
  xy_wap_embed_insight_label_config: XyWapEmbedInsightLabelConfig;
  xy_wap_embed_insight_qa_rule_config: XyWapEmbedInsightQaRuleConfig;
  xy_wap_embed_insight_sync_cursor: XyWapEmbedInsightSyncCursor;
  xy_wap_embed_logical_session: XyWapEmbedLogicalSession;
  xy_wap_embed_logical_session_message: XyWapEmbedLogicalSessionMessage;
  xy_wap_embed_msg_audit_info: XyWapEmbedMsgAuditInfo;
  xy_wap_embed_msg_audit_info_extend: XyWapEmbedMsgAuditInfoExtend;
  xy_wap_embed_session_action_item: XyWapEmbedSessionActionItem;
  xy_wap_embed_session_insight_current: XyWapEmbedSessionInsightCurrent;
  xy_wap_embed_session_insight_snapshot: XyWapEmbedSessionInsightSnapshot;
  xy_wap_embed_session_problem_resolution: XyWapEmbedSessionProblemResolution;
  xy_wap_embed_session_qa_finding: XyWapEmbedSessionQaFinding;
  xy_wap_embed_session_summary: XyWapEmbedSessionSummary;
  xy_wap_embed_session_sentiment: XyWapEmbedSessionSentiment;
  xy_wap_embed_session_tag: XyWapEmbedSessionTag;
  xy_wap_embed_session_entity: XyWapEmbedSessionEntity;
  xy_wap_embed_session_intent: XyWapEmbedSessionIntent;
  xy_wap_embed_session_faq_candidate: XyWapEmbedSessionFaqCandidate;
  xy_wap_embed_sessionization_config: XyWapEmbedSessionizationConfig;
  xy_wap_embed_sider_bar_config: XyWapEmbedSiderBarConfig;
  xy_wap_embed_sub_user: XyWapEmbedSubUser;
  xy_wap_embed_sub_user_session: XyWapEmbedSubUserSession;
  xy_wap_embed_user_relation: XyWapEmbedUserRelation;
  xy_wap_embed_user_seat: XyWapEmbedUserSeat;
  xy_wap_embed_user_seat_sub_relation: XyWapEmbedUserSeatSubRelation;
}

export type Database = DB;
