import type {
  InsightEntityDictionaryItem,
  InsightIntentConfig,
  InsightLabelConfig,
  InsightQaRuleConfig,
  InsightSettingsResponse,
} from "@chatai/contracts";

export const systemPresetCodePrefix = "sys_";
// Preset candidate ids use the `preset:` prefix so the web UI can distinguish
// templates that have not been inserted into tenant config tables yet.

export const SYSTEM_PRESET_INTENT_CONFIGS: InsightIntentConfig[] = [
  {
    description: "无具体业务诉求，仅打招呼或随性闲聊",
    status: 0,
    id: "preset:sys_greeting_chat",
    intentCode: "sys_greeting_chat",
    intentName: "寒暄闲聊",
    negativeExamples: ["这个多少钱"],
    positiveExamples: ["你好", "在吗"],
    weight: 1,
  },
  {
    description: "客户询问规格、材质、尺码、功能、使用方法等商品信息",
    status: 0,
    id: "preset:sys_product_consult",
    intentCode: "sys_product_consult",
    intentName: "产品咨询",
    negativeExamples: ["快递什么时候到"],
    positiveExamples: ["这个是什么材质", "160穿什么尺码"],
    weight: 8,
  },
  {
    description: "客户询问价格、折扣、优惠券、满减等价格相关问题",
    status: 0,
    id: "preset:sys_price_consult",
    intentCode: "sys_price_consult",
    intentName: "价格咨询",
    negativeExamples: ["这个怎么使用"],
    positiveExamples: ["这个多少钱", "有没有优惠券"],
    weight: 8,
  },
  {
    description: "客户询问直播、秒杀、满减、赠品、限时活动等活动信息",
    status: 0,
    id: "preset:sys_campaign_consult",
    intentCode: "sys_campaign_consult",
    intentName: "活动咨询",
    negativeExamples: ["会员积分怎么用"],
    positiveExamples: ["今天直播有什么活动", "现在下单有赠品吗"],
    weight: 8,
  },
  {
    description: "客户询问会员、积分、优惠券、储值、专属权益等私域权益",
    status: 0,
    id: "preset:sys_benefit_consult",
    intentCode: "sys_benefit_consult",
    intentName: "权益咨询",
    negativeExamples: ["这件还有库存吗"],
    positiveExamples: ["会员券怎么领", "积分可以抵扣吗"],
    weight: 8,
  },
  {
    description: "客户询问是否有货、补货时间、颜色尺码库存",
    status: 0,
    id: "preset:sys_stock_consult",
    intentCode: "sys_stock_consult",
    intentName: "库存咨询",
    negativeExamples: ["我要改地址"],
    positiveExamples: ["这个颜色还有吗", "什么时候补货"],
    weight: 7,
  },
  {
    description: "客户询问如何下单、拍哪个链接、组合购买等问题",
    status: 0,
    id: "preset:sys_order_consult",
    intentCode: "sys_order_consult",
    intentName: "下单咨询",
    negativeExamples: ["订单地址写错了"],
    positiveExamples: ["怎么买", "我应该拍哪个链接"],
    weight: 7,
  },
  {
    description: "客户要求修改地址、规格、颜色、备注等订单信息",
    status: 0,
    id: "preset:sys_order_modify",
    intentCode: "sys_order_modify",
    intentName: "订单修改",
    negativeExamples: ["还没下单怎么选"],
    positiveExamples: ["地址写错了能改吗", "颜色拍错了"],
    weight: 8,
  },
  {
    description: "客户询问发货时间、快递进度、物流异常",
    status: 0,
    id: "preset:sys_logistics_consult",
    intentCode: "sys_logistics_consult",
    intentName: "物流咨询",
    negativeExamples: ["我要申请退款"],
    positiveExamples: ["什么时候发货", "快递一直没更新"],
    weight: 8,
  },
  {
    description: "客户咨询退货、退款、换货、售后处理进度",
    status: 0,
    id: "preset:sys_after_sale",
    intentCode: "sys_after_sale",
    intentName: "售后退款",
    negativeExamples: ["这个是什么材质"],
    positiveExamples: ["我要申请退款", "可以换货吗"],
    weight: 9,
  },
  {
    description: "客户反馈破损、错发、漏发、瑕疵、效果不符等问题",
    status: 0,
    id: "preset:sys_quality_feedback",
    intentCode: "sys_quality_feedback",
    intentName: "质量反馈",
    negativeExamples: ["价格还能便宜吗"],
    positiveExamples: ["收到是坏的", "少发了一件"],
    weight: 9,
  },
  {
    description: "客户表达不满、催促处理、质疑服务或要求补偿",
    status: 0,
    id: "preset:sys_complaint",
    intentCode: "sys_complaint",
    intentName: "投诉抱怨",
    negativeExamples: ["你好在吗"],
    positiveExamples: ["你们服务太差了", "我要投诉"],
    weight: 10,
  },
];

export const SYSTEM_PRESET_LABEL_CONFIGS: InsightLabelConfig[] = [
  {
    description: "客户明确表达购买意向、询价、库存确认或下单前关键信息确认",
    status: 0,
    id: "preset:sys_high_purchase_intent",
    labelCode: "sys_high_purchase_intent",
    labelName: "高购买意向",
    negativeExamples: ["客户只表达感谢"],
    positiveExamples: ["现在拍什么时候发", "还有优惠吗"],
  },
  {
    description: "客户反复关注优惠、比价、满减、赠品或价格是否还能降低",
    status: 0,
    id: "preset:sys_price_sensitive",
    labelCode: "sys_price_sensitive",
    labelName: "价格敏感",
    negativeExamples: ["客户询问尺码"],
    positiveExamples: ["能不能再便宜点", "有没有优惠券"],
  },
];

export const SYSTEM_PRESET_QA_RULE_CONFIGS: InsightQaRuleConfig[] = [
  {
    applicableScene: "全场景",
    description: "检查客服服务态度是否礼貌、耐心、专业",
    status: 0,
    id: "preset:sys_service_attitude",
    judgmentCriteria: "客服需使用礼貌用语，不得出现反问、讽刺、推诿或不耐烦表达；客户情绪激动时应先安抚再处理问题",
    negativeExamples: ["你自己看说明啊", "这不是我们的问题", "我都说了好几遍了"],
    positiveExamples: ["非常抱歉给您带来不便，我来帮您处理", "理解您的心情，我这边马上帮您核实"],
    ruleCode: "sys_service_attitude",
    ruleName: "服务态度",
    severity: "medium",
  },
  {
    applicableScene: "客户提出明确诉求或问题时",
    description: "检查客服是否给出明确后续处理动作",
    status: 0,
    id: "preset:sys_follow_up_clear",
    judgmentCriteria: "对需要后续处理的问题，客服应确认客户的问题并告知下一步处理动作或预计时间，不能只回复“好的”“收到”等无实质内容",
    negativeExamples: ["好的", "收到", "我看看", "知道了"],
    positiveExamples: ["已收到，这边帮您查一下物流状态，稍等", "明白您的情况，我们会尽快为您安排补发，预计24小时内处理"],
    ruleCode: "sys_follow_up_clear",
    ruleName: "高效跟进",
    severity: "high",
  },
];

export const SYSTEM_PRESET_ENTITY_DICTIONARY: InsightEntityDictionaryItem[] = [
  {
    aliases: ["直播价", "直播专属", "限时秒杀"],
    entityCode: "sys_live_room_promotion",
    entityName: "直播间活动",
    status: 0,
    id: "preset:sys_live_room_promotion",
  },
  {
    aliases: ["会员券", "店铺券", "满减券", "优惠码"],
    entityCode: "sys_member_coupon",
    entityName: "会员优惠券",
    status: 0,
    id: "preset:sys_member_coupon",
  },
];

export const DEFAULT_INSIGHT_SETTINGS: InsightSettingsResponse = {
  analysisPolicy: {
    finalAnalysisEnabled: true,
    liveAnalysisEnabled: true,
    liveMinIntervalMinutes: 15,
    liveMinNewMeaningfulMessages: 20,
    lowConfidenceThreshold: 0.6,
    minAnalysisMessages: 5,
    ruleFallbackEnabled: true,
  },
  featureConfig: {
    entityEnabled: true,
    insightAvailable: true,
    insightEnabled: false,
    intentEnabled: true,
    labelEnabled: true,
    qaEnabled: true,
    todoEnabled: true,
  },
  entityDictionary: [],
  intentConfigs: [],
  labelConfigs: [],
  qaRuleConfigs: [],
  sessionization: {
    analysisDelayMinutes: 10,
    hardMaxDurationHours: 8,
    idleTimeoutMinutes: 120,
    lateArrivalWindowMinutes: 30,
    preset: "custom",
  },
};
