import { describe, expect, it } from "vitest";
import {
  hashPassword,
  verifyPassword,
} from "../../../src/modules/auth/password.service.js";

describe("password service", () => {
  it("verifies Argon2 PHC hashes with padded base64 salt and hash fields", async () => {
    const paddedHash =
      "$argon2id$v=19$m=19456,t=2,p=1$oDLkQ/9STV0AWBidrefwow==$fCe4n8UW9lcREtMZMBZYOD6YF/EDmZChtBtt332ZUpA=";
    const normalizedHash =
      "$argon2id$v=19$m=19456,t=2,p=1$oDLkQ/9STV0AWBidrefwow$fCe4n8UW9lcREtMZMBZYOD6YF/EDmZChtBtt332ZUpA";
    const expected = await verifyPassword(normalizedHash, "wrong-password");

    await expect(verifyPassword(paddedHash, "wrong-password")).resolves.toBe(
      expected,
    );
  });

  it("keeps verifying hashes generated by this service", async () => {
    const hash = await hashPassword("correct-password");

    await expect(verifyPassword(hash, "correct-password")).resolves.toBe(true);
    await expect(verifyPassword(hash, "wrong-password")).resolves.toBe(false);
  });
});
