const DOUBAO_SEED_20_LITE = "ep-20260227145914-nxcmn";
const DOUBAO_SEED_20_MINI = "ep-20260724141445-7d6qm";

const VOLCENGINE_ARK_DEFAULT_MODEL = DOUBAO_SEED_20_LITE;
const VOLCENGINE_ARK_LITE_MODEL = DOUBAO_SEED_20_MINI;

export const VOLCENGINE_ARK_MEMORY_MODEL = VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_INSIGHTS_ANALYSIS_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_INSIGHTS_CLASSIFICATION_MODEL =
  VOLCENGINE_ARK_LITE_MODEL;
export const VOLCENGINE_ARK_WORKFLOW_AI_INTENT_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_WORKFLOW_AI_COLLECT_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
