const DOUBAO_SEED_LITE = "ep-20260911170827-l69hp";
const DOUBAO_SEED_MINI = "ep-20260924194002-9j9nf";

const VOLCENGINE_ARK_DEFAULT_MODEL = DOUBAO_SEED_LITE;
const VOLCENGINE_ARK_LITE_MODEL = DOUBAO_SEED_MINI;

export const VOLCENGINE_ARK_MEMORY_MODEL = VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_INSIGHTS_ANALYSIS_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_INSIGHTS_CLASSIFICATION_MODEL =
  VOLCENGINE_ARK_LITE_MODEL;
export const VOLCENGINE_ARK_AI_EDIT_MODEL = VOLCENGINE_ARK_LITE_MODEL;
export const VOLCENGINE_ARK_WORKFLOW_AI_INTENT_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
export const VOLCENGINE_ARK_WORKFLOW_AI_COLLECT_MODEL =
  VOLCENGINE_ARK_DEFAULT_MODEL;
