export const WORKFLOW_ENTRY_WINDOW_MAX_DAYS = 90;
export const WORKFLOW_ENTRY_WINDOW_MAX_HOURS = 2_160;
export const WORKFLOW_RUN_RETENTION_DAYS = 180;
export const WORKFLOW_TASK_OUTBOX_RETENTION_DAYS = 30;
