name: Sync GitHub to Gitee
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git ownership
        run: git config --global --add safe.directory /github/workspace

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: https://github.com/dtminds/ChatAI.git
          destination-repo: git@gitee.com:dtminds/ChatAI.git
